{ lib
, stdenv
, fetchFromGitHub
, swift
, swiftpm
, swiftPackages
, darwin
, xcbuild
, cacert # Required by git during build process
, asciidoctor
, gnused
, tree
, nur # for xcodegen
}:

stdenv.mkDerivation rec {
  pname = "aerospace";
  version = "v0.7.1-Beta";

  src = fetchFromGitHub {
    owner = "nikitabobko";
    repo = "AeroSpace";
    rev = "${version}";
    sha256 = "sha256-dUnbTnsFq/q5mFFai01z+Oxx5yPGScUXFJ7PB/bEgls=";
  };

  patches = [
  ];


  nativeBuildInputs = [
    darwin.apple_sdk.frameworks.Foundation
  ];

  buildInputs = [
    swift
    swiftpm
    darwin.apple_sdk.frameworks.Foundation
    swiftPackages.XCTest
    swiftPackages.Foundation
    xcbuild # for xcrun
    cacert
    asciidoctor
    gnused
    tree
    nur.repos.endle.xcodegen
  ];


  configurePhase = ''
set -e # Exit if one of commands exit with non-zero exit code
set -u # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error
set -o pipefail # Any command failed in the pipe fails the whole pipe
set -x # Print shell commands as they are executed (or you can try -v which is less verbose)


version=$(head -1 ./version.txt | awk '{print $1}')
build_number=$(tail -1 ./version.txt | awk '{print $1}')

cat > LocalPackage/Sources/Common/versionGenerated.swift <<EOF
// FILE IS GENERATED BY generate.sh
public let aeroSpaceAppVersion = "$version"
EOF

# GNU sed
sed -i "s/CURRENT_PROJECT_VERSION.*/CURRENT_PROJECT_VERSION: $build_number # GENERATED BY generate.sh/" ./project.yml
sed -i "s/MARKETING_VERSION.*/MARKETING_VERSION: $version # GENERATED BY generate.sh/" ./project.yml

xcodegen # https://github.com/yonaskolb/XcodeGen
  '';

  buildPhase = ''
    ls
  '';
  installPhase = ''
    mkdir -p $out/bin
    cp .build/release/xcodegen $out/bin
  '';

  enableParallelBuilding = true;


  meta = with lib; {
    homepage = "https://github.com/nikitabobko/AeroSpace";
    description = " an i3-like tiling window manager for macOS";
    longDescription = ''
      XcodeGen is a command line tool written in Swift that generates your Xcode project using your folder structure and a project spec.
    '';
    license = licenses.mit;
    platforms = platforms.darwin;
    maintainers = with maintainers; [ endle ];
  };
}
